name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Write File
        uses: DamianReeves/write-file-action@v1.2
        with:
          path: thing.txt
          contents: "Hello"
      - name: "Create Release"
        uses: ncipollo/release-action@v1.13.0
        with:
          artifacts: "thing.txt"
          tag: "6.06"
