name: Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build606:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install debootstrap
      - run: sudo debootstrap --arch=i386 dapper http://old-releases.ubuntu.com/ubuntu/ root
      - run: mksquashfs root 6.06-i386.squashfs
      - name: "Create Release"
        uses: ncipollo/release-action@v1.13.0
        with:
          artifacts: "6.06-i386.squashfs"
          tag: "6.06"
