name: Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build606:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Tag
        run: echo "TAG_NAME=$(date "+%Y-%m-%d")" >> $GITHUB_ENV
      - run: sudo apt-get install debootstrap
      - run: sudo debootstrap --arch=i386 dapper root http://old-releases.ubuntu.com/ubuntu/
      - run: sudo mksquashfs root 6.06-i386.squashfs
      - name: "Create Release"
        uses: ncipollo/release-action@v1.13.0
        with:
          artifacts: "6.06-i386.squashfs"
          tag: ${{ env.TAG_NAME }}
