name: Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
env:
  date: $(date "+%d-%m-%y")
jobs:
  build606:
    runs-on: ubuntu-latest
    steps:
      - run: date_formatted=$(date "+%Y-%m-%d") && echo "TAG_NAME=$date_formatted" >> $GITHUB_OUTPUT
      - run: sudo apt-get install debootstrap
      - run: sudo debootstrap --arch=i386 dapper root http://old-releases.ubuntu.com/ubuntu/
      - run: sudo mksquashfs root 6.06-i386.squashfs
      - name: "Create Release"
        uses: ncipollo/release-action@v1.13.0
        with:
          artifacts: "6.06-i386.squashfs"
          tag: ${{ steps.generate_tag.outputs.TAG_NAME }}
